### ISSUE TITLE
입수데이터 A003_2018 

### ISSUE THREAD

**Issue by sangkim22** [ypspy/dart-scraping#28]
안녕하세요 올려주신 입수데이터 잘 활용하고 있습니다.

그런데 A003_2018의 데이터에 문제가 있는 거 같습니다. 압축파일을 해제할 수가 없네요.

올려주신 코드는 정말 감사합니다. 큰 도움이 되었습니다.

**Comment by ypspy** [comment]
도움이 되셨다니 다행입니다. 

A003_2018은 저도 다시 받아보니 손상된 파일이라고 하는데 압축은 풀리네요. 다시 압축해서 파일 교체하였습니다. 저는 반디집을 사용하는데, 테스트해보니 이번에는 손상 표시가 없네요. 확인해보시길 바랍니다. 혹시 여전히 압축 해제가 안된다면 말씀해주세요. 따로 보내드리던가 하겠습니다. 본 이슈는 Close 하겠습니다. 감사합니다.
